### PR TITLE
Merge unnoficial IntelliJ plugin

### PR DESCRIPTION
**Pull request by Nxllpointer**
Currently includes:
- The plugin base 
- Suppression of "Unused" warnings

### CODE REVIEW

**Review by bitspittle — APPROVED** [review]
This is a great foundation. Thank you so much!

Note that I'll probably downgrade the version for a bit, maybe 0.6 or something, but we can do that after merging.

**Comment by Nxllpointer** [comment]
> Note that I'll probably downgrade the version for a bit, maybe 0.6 or something, but we can do that after merging.

I think that could be a little problematic. I actually increased the min version, because the with default version used by the project wizard, the kotlin plugin is incompatible with more recent versions of Intellij (see da380bd). You can try getting it as low as possible though

**Comment by bitspittle** [comment]
> I think [downgrading the version] could be a little problematic.

I think we're talking about different versions? I meant this one: https://github.com/varabyte/kobweb-intellij-plugin/commit/76599d1de4571d6ce6619a66c86b7c8a32ae6b90

**Comment by Nxllpointer** [comment]
Oh yes lol. Turns out 2am is too late to comprehend comments. Downgrading that version is absolutely fine

**Pull request merged**
